export const upcomingMovies = [
  {
    id: 1,
    title: "Moana",
    posterUrl: "https://image.tmdb.org/t/p/w500/zKVgiv5qHCvCLT4A2ymJi5QeXDH.jpg",
    publicReleaseDate: "2026-07-10",
    description: "A live-action reimagining of Disney’s ocean adventure, following Moana and Maui on a mythic voyage across the Pacific.",
    director: "Thomas Kail",
    worldPremiere: "2026-07-06 — El Capitan Theatre, Hollywood",
    categories: ["Adventure", "Family", "Fantasy", "Musical"],
    mainCast: ["Catherine Laga'aia", "Dwayne Johnson", "Rena Owen", "John Tui"],
    runtime: "115 min",
    releaseVenue: "Century Cinemax Sarit, Nairobi"
  },
  {
    id: 2,
    title: "Evil Dead Burn",
    posterUrl: "https://image.tmdb.org/t/p/w500/ztadKzIIR0ERYqpHteaPFtk7inP.jpg",
    publicReleaseDate: "2026-07-10",
    description: "A standalone Evil Dead entry introducing a new group of characters facing a supernatural nightmare.",
    director: "Sébastien Vaniček",
    worldPremiere: "2026-07-08 — Fantastic Fest Midnight Showcase, Austin",
    categories: ["Horror", "Mystery", "Fantasy"],
    mainCast: ["Hunter Doohan", "Luciane Buchanan", "Souheila Yacoub", "Erroll Shand"],
    runtime: "110 min",
    releaseVenue: "Anga Diamond Plaza, Nairobi"
  },
  {
    id: 3,
    title: "The Invite",
    posterUrl: "https://image.tmdb.org/t/p/w500/b7Dr8Chzse8VagexAporUu2RtLx.jpg",
    publicReleaseDate: "2026-07-10",
    description: "A sharp relationship comedy-drama built around a high-pressure social event where hidden motives surface.",
    director: "Nicholas Stoller",
    worldPremiere: "2026-07-07 — Tribeca Special Preview, New York",
    categories: ["Comedy", "Drama", "Romance"],
    mainCast: ["Seth Rogen", "Olivia Wilde", "Penélope Cruz", "Edward Norton"],
    runtime: "107 min",
    releaseVenue: "Century Cinemax Two Rivers, Nairobi"
  },
  {
    id: 4,
    title: "The Isolate Thief",
    posterUrl: "https://image.tmdb.org/t/p/w500/1hbj6QirIAWmAx6T3IrRnBNTEyj.jpg",
    publicReleaseDate: "2026-07-10",
    description: "A frontier-style action drama about a fugitive, a stolen fortune, and a final crossing through hostile territory.",
    director: "John Suits",
    worldPremiere: "2026-07-05 — Denver Frontier Film Night",
    categories: ["Action", "Drama", "Western"],
    mainCast: ["Sean Bean", "Joe Pantoliano", "Mackenzie Foy", "Odeya Rush"],
    runtime: "95 min",
    releaseVenue: "Prestige Cinema, Nairobi"
  },
  {
    id: 5,
    title: "Night Nurse",
    posterUrl: "https://image.tmdb.org/t/p/w500/tzhBAhN35YjobVG3Ubm3ERnzhBL.jpg",
    publicReleaseDate: "2026-07-10",
    description: "A tense psychological thriller set during a night shift where a caretaker begins doubting what is real.",
    director: "Georgia Bernstein",
    worldPremiere: "2026-07-04 — Fantasia Industry Screening, Montreal",
    categories: ["Thriller", "Horror"],
    mainCast: ["Mimi Rogers", "Bruce McKenzie", "Eleonore Hendricks", "Cemre Paksoy"],
    runtime: "96 min",
    releaseVenue: "Anga CBD, Nairobi"
  },
  {
    id: 6,
    title: "Mockbuster",
    posterUrl: "https://image.tmdb.org/t/p/w500/wcjyHnvWtohsGrZHcNTEBwO2ooY.jpg",
    publicReleaseDate: "2026-07-10",
    description: "A documentary-comedy look at low-budget genre filmmaking and the culture around fast-turnaround cinema.",
    director: "Calum Waddell",
    worldPremiere: "2026-07-03 — Burbank Indie Film Forum",
    categories: ["Documentary", "Comedy", "Horror", "Sci-Fi"],
    mainCast: ["Eric Roberts", "Michael Paré", "Michelle Bauer", "Michael Philippou"],
    runtime: "90 min",
    releaseVenue: "Unseen Nairobi Rooftop Cinema"
  },
  {
    id: 7,
    title: "Reading Lolita in Tehran",
    posterUrl: "https://image.tmdb.org/t/p/w500/69WQXk3Omh0IKles3Pcmlhvo3En.jpg",
    publicReleaseDate: "2026-07-10",
    description: "A literary drama about women meeting in secret to read forbidden Western classics during political upheaval.",
    director: "Eran Riklis",
    worldPremiere: "2026-07-02 — Karlovy Vary Special Presentation",
    categories: ["Biography", "Drama"],
    mainCast: ["Golshifteh Farahani", "Zar Amir Ebrahimi", "Mina Kavani", "Reza Diako"],
    runtime: "107 min",
    releaseVenue: "Alliance Française de Nairobi"
  },
  {
    id: 8,
    title: "Baby Doe",
    posterUrl: "https://image.tmdb.org/t/p/w500/miMQlKiKLJ73xAXe6PDNBfxw2Jv.jpg",
    publicReleaseDate: "2026-07-10",
    description: "A documentary following a long, emotional search for identity, family history, and accountability.",
    director: "Jessica Earnshaw",
    worldPremiere: "2026-07-01 — DOC NYC Summer Preview",
    categories: ["Documentary"],
    mainCast: ["Gail Eastwood-Ritchey"],
    runtime: "100 min",
    releaseVenue: "Nairobi Film Centre"
  },
  {
    id: 9,
    title: "Black Chariot",
    posterUrl: "https://image.tmdb.org/t/p/w500/cHoIlL1K5R4K85JjTAMVlJkCrFs.jpg",
    publicReleaseDate: "2026-07-10",
    description: "A restored drama release centered on power, faith, and social pressure in a changing community.",
    director: "Robert L. Goodwin",
    worldPremiere: "2026-07-06 — Museum of Modern Art Restoration Night, New York",
    categories: ["Drama"],
    mainCast: ["Bernie Casey", "Barbara O", "Richard Elkins", "Paulene Myers"],
    runtime: "90 min",
    releaseVenue: "Kenya National Theatre Screening Room"
  },
  {
    id: 10,
    title: "Crossing",
    posterUrl: "https://image.tmdb.org/t/p/w500/bywFoHoLZvW2vxDc7n4ToAKkR0y.jpg",
    publicReleaseDate: "2026-07-10",
    description: "A historical war drama about soldiers navigating sacrifice, loyalty, and survival during a decisive campaign.",
    director: "Guan Hu",
    worldPremiere: "2026-07-04 — Shanghai Grand Theatre",
    categories: ["Action", "History", "War"],
    mainCast: ["Ye Liu", "Lei Wang", "Bingkun Cao", "Dong Jin"],
    runtime: "122 min",
    releaseVenue: "Century Cinemax Garden City, Nairobi"
  },
  {
    id: 11,
    title: "Barrio Triste",
    posterUrl: "https://image.tmdb.org/t/p/w500/w2zymRakHhwKUnRCLPKrBiL8inL.jpg",
    publicReleaseDate: "2026-07-10",
    description: "A stylized urban story following restless young characters through a surreal night in a fractured city.",
    director: "Stillz",
    worldPremiere: "2026-07-02 — Locarno Preview Night",
    categories: ["Drama", "Experimental"],
    mainCast: ["Brahian Acevedo", "Juan Pablo Baena", "Samuel Andrés Celis"],
    runtime: "94 min",
    releaseVenue: "Unseen Nairobi Rooftop Cinema"
  },
  {
    id: 12,
    title: "Westhampton",
    posterUrl: "https://image.tmdb.org/t/p/w500/3YvIAVjzPr24xqY95gG2ygwI6V4.jpg",
    publicReleaseDate: "2026-07-10",
    description: "A coastal-town drama about reputation, regret, and the return of a figure everyone thought had disappeared.",
    director: "Christian Nilsson",
    worldPremiere: "2026-07-05 — Hamptons Summer Film Preview",
    categories: ["Drama", "Mystery"],
    mainCast: ["RJ Mitte", "Finn Wittrock", "Tovah Feldshuh", "Jake Weary"],
    runtime: "101 min",
    releaseVenue: "Prestige Cinema, Nairobi"
  },
  {
    id: 13,
    title: "Food Roots",
    posterUrl: "https://image.tmdb.org/t/p/w500/dJiFPoWy0kfuQQItHbdQw37jCuR.jpg",
    publicReleaseDate: "2026-07-16",
    description: "A food-culture documentary tracing how family recipes preserve migration stories and regional identity.",
    director: "Michele Josue",
    worldPremiere: "2026-07-09 — Napa Valley Film & Food Preview",
    categories: ["Documentary", "Culture", "Food"],
    mainCast: ["Featured chefs", "Family historians", "Community cooks"],
    runtime: "88 min",
    releaseVenue: "Alliance Française de Nairobi"
  },
  {
    id: 14,
    title: "The Odyssey",
    posterUrl: "https://image.tmdb.org/t/p/w500/5rhTDKUhPYvpdQIijFIs5VoWsON.jpg",
    publicReleaseDate: "2026-07-17",
    description: "Christopher Nolan adapts Homer’s epic, following Odysseus after the Trojan War as he struggles to return home.",
    director: "Christopher Nolan",
    worldPremiere: "2026-07-13 — Odeon Luxe Leicester Square, London",
    categories: ["Adventure", "Drama", "Fantasy"],
    mainCast: ["Matt Damon", "Tom Holland", "Anne Hathaway", "Zendaya"],
    runtime: "172 min",
    releaseVenue: "IMAX Garden City, Nairobi"
  },
  {
    id: 15,
    title: "American Pachuco: The Legend of Luis Valdez",
    posterUrl: "https://image.tmdb.org/t/p/w500/rh7FjvBcvdOTEFMArZvFmeWEiJv.jpg",
    publicReleaseDate: "2026-07-17",
    description: "A documentary portrait of playwright and filmmaker Luis Valdez and his influence on Chicano theatre and cinema.",
    director: "Daniel Valdez",
    worldPremiere: "2026-07-11 — Los Angeles Latino International Film Festival",
    categories: ["Documentary", "Biography"],
    mainCast: ["Herman Gallegos", "Jessica Govea", "Taylor Hackford", "Dolores Huerta"],
    runtime: "92 min",
    releaseVenue: "Nairobi Film Centre"
  },
  {
    id: 16,
    title: "Dastaar",
    posterUrl: "https://image.tmdb.org/t/p/w500/b7Dr8Chzse8VagexAporUu2RtLx.jpg",
    publicReleaseDate: "2026-07-17",
    description: "A family drama about identity, duty, and tradition as a young man confronts the expectations surrounding him.",
    director: "Manav Shah",
    worldPremiere: "2026-07-12 — Chandigarh Premiere Hall",
    categories: ["Drama", "Family"],
    mainCast: ["Gippy Grewal", "Tania", "Gurpreet Ghuggi"],
    runtime: "130 min",
    releaseVenue: "Century Cinemax Junction, Nairobi"
  },
  {
    id: 17,
    title: "Horsegirls",
    posterUrl: "https://image.tmdb.org/t/p/w500/b7Dr8Chzse8VagexAporUu2RtLx.jpg",
    publicReleaseDate: "2026-07-17",
    description: "A coming-of-age comedy-drama about obsession, belonging, and the intense bonds formed around a riding stable.",
    director: "Lauren Meyering",
    worldPremiere: "2026-07-10 — Sundance London Summer Selection",
    categories: ["Comedy", "Drama"],
    mainCast: ["Lillian Carrier", "Gretchen Mol", "Jerrod Haynes", "Tony Hale"],
    runtime: "101 min",
    releaseVenue: "Unseen Nairobi Rooftop Cinema"
  },
  {
    id: 18,
    title: "The Kidnapping of Arabella",
    posterUrl: "https://image.tmdb.org/t/p/w500/kiFacg75KVjy0AM3S4QmbPas8zL.jpg",
    publicReleaseDate: "2026-07-17",
    description: "A crime drama about a staged abduction that spins into a darker, stranger situation than anyone planned.",
    director: "Carolina Cavalli",
    worldPremiere: "2026-07-09 — Rome Cinema Showcase",
    categories: ["Comedy", "Crime", "Drama", "Thriller"],
    mainCast: ["Benedetta Porcaroli", "Lucrezia Guglielmino", "Chris Pine", "Marco Bonadei"],
    runtime: "107 min",
    releaseVenue: "Anga Diamond Plaza, Nairobi"
  },
  {
    id: 19,
    title: "Bad Counselors",
    posterUrl: "https://image.tmdb.org/t/p/w500/b7Dr8Chzse8VagexAporUu2RtLx.jpg",
    publicReleaseDate: "2026-07-23",
    description: "A family comedy about chaotic camp staff trying to save a summer program from complete collapse.",
    director: "Todd Holland",
    worldPremiere: "2026-07-19 — Fathom Family Preview, Dallas",
    categories: ["Comedy", "Family"],
    mainCast: ["Matt Cornett", "Missi Pyle", "Chris Klein", "Richard T. Jones"],
    runtime: "100 min",
    releaseVenue: "Century Cinemax Two Rivers, Nairobi"
  },
  {
    id: 20,
    title: "Sia: Nostalgic for The Present",
    posterUrl: "https://image.tmdb.org/t/p/w500/b7Dr8Chzse8VagexAporUu2RtLx.jpg",
    publicReleaseDate: "2026-07-23",
    description: "A concert-film event built around Sia’s stage performance, music direction, and visual spectacle.",
    director: "Daniel Askill",
    worldPremiere: "2026-07-20 — Event Cinema Global Preview, London",
    categories: ["Music", "Concert"],
    mainCast: ["Sia"],
    runtime: "75 min",
    releaseVenue: "Anga Diamond Plaza, Nairobi"
  },
  {
    id: 21,
    title: "Her Private Hell",
    posterUrl: "https://image.tmdb.org/t/p/w500/aLVkiINlIeCkcZIzb7XHzPYgO6L.jpg",
    publicReleaseDate: "2026-07-24",
    description: "A neon-lit psychological thriller about isolation, obsession, and a private world that starts to collapse.",
    director: "Nicolas Winding Refn",
    worldPremiere: "2026-07-18 — Cannes Midnight Encore, Paris",
    categories: ["Crime", "Drama", "Thriller"],
    mainCast: ["Sophie Thatcher", "Charles Melton", "Havana Rose Liu", "Dougray Scott"],
    runtime: "109 min",
    releaseVenue: "Prestige Cinema, Nairobi"
  },
  {
    id: 22,
    title: "Motor City",
    posterUrl: "https://image.tmdb.org/t/p/w500/7zNmJP6z6mDAp4LouacYkGSBUQv.jpg",
    publicReleaseDate: "2026-07-24",
    description: "A gritty action drama set against Detroit’s muscle-car mythology and a revenge mission decades in the making.",
    director: "Potsy Ponciroli",
    worldPremiere: "2026-07-18 — Detroit Fox Theatre",
    categories: ["Action", "Drama", "Crime"],
    mainCast: ["Alan Ritchson", "Ben Foster", "Pablo Schreiber", "Shailene Woodley"],
    runtime: "104 min",
    releaseVenue: "Century Cinemax Garden City, Nairobi"
  },
  {
    id: 23,
    title: "Pinocchio: Unstrung",
    posterUrl: "https://image.tmdb.org/t/p/w500/zKVgiv5qHCvCLT4A2ymJi5QeXDH.jpg",
    publicReleaseDate: "2026-07-24",
    description: "A dark fantasy reworking of the Pinocchio myth, reframed as a suspense-driven genre story.",
    director: "Rhys Frake-Waterfield",
    worldPremiere: "2026-07-17 — FrightFest Preview, London",
    categories: ["Fantasy", "Horror", "Thriller"],
    mainCast: ["Richard Brake", "Robert Englund", "Cameron Bell", "Jessica Balmer"],
    runtime: "82 min",
    releaseVenue: "Anga CBD, Nairobi"
  },
  {
    id: 24,
    title: "Cruel Hands",
    posterUrl: "https://image.tmdb.org/t/p/w500/aLVkiINlIeCkcZIzb7XHzPYgO6L.jpg",
    publicReleaseDate: "2026-07-24",
    description: "A compact thriller about a desperate group trapped inside a scheme that turns against them.",
    director: "Steven Kastrissios",
    worldPremiere: "2026-07-16 — Melbourne Genre Film Night",
    categories: ["Horror", "Thriller"],
    mainCast: ["Mavournee Hazel", "Ana Benham", "Max Cattana", "Gerard Colins"],
    runtime: "76 min",
    releaseVenue: "Unseen Nairobi Rooftop Cinema"
  },
  {
    id: 25,
    title: "Hadestown: The Musical",
    posterUrl: "https://image.tmdb.org/t/p/w500/zKVgiv5qHCvCLT4A2ymJi5QeXDH.jpg",
    publicReleaseDate: "2026-07-24",
    description: "A filmed stage presentation of the acclaimed musical retelling of Orpheus and Eurydice.",
    director: "Rachel Chavkin",
    worldPremiere: "2026-07-21 — Broadway Event Cinema Premiere, New York",
    categories: ["Musical", "Stage", "Drama"],
    mainCast: ["Original stage ensemble"],
    runtime: "120 min",
    releaseVenue: "Kenya National Theatre Screening Room"
  },
  {
    id: 26,
    title: "Haunted Heist",
    posterUrl: "https://image.tmdb.org/t/p/w500/zKVgiv5qHCvCLT4A2ymJi5QeXDH.jpg",
    publicReleaseDate: "2026-07-24",
    description: "A comedy-mystery about thieves whose robbery plan is complicated by a building with a supernatural reputation.",
    director: "Malcolm D. Lee",
    worldPremiere: "2026-07-20 — Atlanta Comedy Film Preview",
    categories: ["Comedy", "Horror", "Mystery"],
    mainCast: ["Brett Gelman", "Tiffany Haddish", "Lil Rel Howery", "Andrew Bachelor"],
    runtime: "87 min",
    releaseVenue: "Century Cinemax Junction, Nairobi"
  },
  {
    id: 27,
    title: "Rosebush Pruning",
    posterUrl: "https://image.tmdb.org/t/p/w500/zKVgiv5qHCvCLT4A2ymJi5QeXDH.jpg",
    publicReleaseDate: "2026-07-24",
    description: "A severe chamber drama about family pressure, inherited resentment, and an elegant house full of secrets.",
    director: "Karim Aïnouz",
    worldPremiere: "2026-07-15 — Venice Classics Preview",
    categories: ["Drama", "Mystery"],
    mainCast: ["Riley Keough", "Callum Turner", "Elle Fanning"],
    runtime: "112 min",
    releaseVenue: "Alliance Française de Nairobi"
  },
  {
    id: 28,
    title: "A Sad and Beautiful World",
    posterUrl: "https://image.tmdb.org/t/p/w500/kiFacg75KVjy0AM3S4QmbPas8zL.jpg",
    publicReleaseDate: "2026-07-24",
    description: "A romantic drama about two people trying to find tenderness and stability in a city shaped by loss.",
    director: "Cyril Aris",
    worldPremiere: "2026-07-14 — Beirut Cinema Days",
    categories: ["Comedy", "Drama", "Romance"],
    mainCast: ["Mounia Akl", "Hasan Akil", "Julia Kassar", "Camille Salameh"],
    runtime: "110 min",
    releaseVenue: "Unseen Nairobi Rooftop Cinema"
  },
  {
    id: 29,
    title: "Sheep in the Box",
    posterUrl: "https://image.tmdb.org/t/p/w500/b7Dr8Chzse8VagexAporUu2RtLx.jpg",
    publicReleaseDate: "2026-07-24",
    description: "A surreal, slow-burn genre film about confinement, memory, and a mysterious object everyone wants opened.",
    director: "Annie Baker",
    worldPremiere: "2026-07-13 — Locarno Midnight Preview",
    categories: ["Drama", "Mystery", "Thriller"],
    mainCast: ["Cast TBA"],
    runtime: "103 min",
    releaseVenue: "Nairobi Film Centre"
  },
  {
    id: 30,
    title: "Spider-Man: Brand New Day",
    posterUrl: "https://image.tmdb.org/t/p/w500/yyB2VJEW3an2xCdcYCPQhn9QERR.jpg",
    publicReleaseDate: "2026-07-31",
    description: "Peter Parker returns for a new Spider-Man chapter after the fallout of his erased public identity.",
    director: "Destin Daniel Cretton",
    worldPremiere: "2026-07-27 — TCL Chinese Theatre, Hollywood",
    categories: ["Action", "Adventure", "Fantasy", "Sci-Fi"],
    mainCast: ["Tom Holland", "Zendaya", "Sadie Sink", "Jacob Batalon"],
    runtime: "145 min",
    releaseVenue: "IMAX Garden City, Nairobi"
  },
  {
    id: 31,
    title: "The Samurai and the Prisoner",
    posterUrl: "https://image.tmdb.org/t/p/w500/1GWVlPM1v6k84LsmDkfDzLlGf0O.jpg",
    publicReleaseDate: "2026-07-31",
    description: "A historical mystery-thriller about captivity, honor, and shifting loyalties during wartime.",
    director: "Kazuya Shiraishi",
    worldPremiere: "2026-07-22 — Tokyo International Preview",
    categories: ["Drama", "History", "Mystery", "Thriller", "War"],
    mainCast: ["Munetaka Aoki", "Tasuku Emoto", "Yamato Kochi", "Ryôta Miyadate"],
    runtime: "147 min",
    releaseVenue: "Century Cinemax Sarit, Nairobi"
  },
  {
    id: 32,
    title: "Terrestrial",
    posterUrl: "https://image.tmdb.org/t/p/w500/g4PBZlyVm2cWgL4jAy7WKEblB4t.jpg",
    publicReleaseDate: "2026-07-31",
    description: "A sci-fi thriller about a man whose ordinary life is disrupted by signals that may not come from Earth.",
    director: "Steve Pink",
    worldPremiere: "2026-07-24 — San Diego Genre Screenings",
    categories: ["Sci-Fi", "Thriller"],
    mainCast: ["Jermaine Fowler", "James Morosini", "Pauline Chalamet", "Edy Modica"],
    runtime: "90 min",
    releaseVenue: "Anga Diamond Plaza, Nairobi"
  },
  {
    id: 33,
    title: "Wild Inside",
    posterUrl: "https://image.tmdb.org/t/p/w500/jk11nlfGnqFnD6LxQHifzyPQCTI.jpg",
    publicReleaseDate: "2026-07-31",
    description: "A nature documentary about survival, adaptation, and the hidden systems that keep wild places alive.",
    director: "Sarah Keo",
    worldPremiere: "2026-07-21 — Jackson Wild Preview, Wyoming",
    categories: ["Documentary", "Nature"],
    mainCast: ["Narrator TBA"],
    runtime: "86 min",
    releaseVenue: "Nairobi National Museum Auditorium"
  },
  {
    id: 34,
    title: "Middle Life",
    posterUrl: "https://image.tmdb.org/t/p/w500/4uXAZRYtcMfoX2XtY1gcUxLHhjj.jpg",
    publicReleaseDate: "2026-07-31",
    description: "A small-scale comedy-drama about aging, ambition, and the awkward reset that comes halfway through adulthood.",
    director: "Noah Pritzker",
    worldPremiere: "2026-07-23 — Nantucket Summer Film Series",
    categories: ["Comedy", "Drama", "Romance"],
    mainCast: ["Leah Fay Goldstein", "Peter Dreimanis", "Luke Lalonde", "Mike D. Smith"],
    runtime: "84 min",
    releaseVenue: "Unseen Nairobi Rooftop Cinema"
  },
  {
    id: 35,
    title: "Ice Cream Man",
    posterUrl: "https://image.tmdb.org/t/p/w500/c987gxFjXqYOxZEZKcTkS1ONTWH.jpg",
    publicReleaseDate: "2026-08-07",
    description: "A suspense film about a neighborhood legend that turns a summer treat into a source of fear.",
    director: "Eli Roth",
    worldPremiere: "2026-08-03 — Fantasia Midnight Programme, Montreal",
    categories: ["Horror", "Thriller"],
    mainCast: ["Ari Millen", "Benjamin Byron Davis", "Karen Cliche", "Sarah Abbott"],
    runtime: "101 min",
    releaseVenue: "Anga CBD, Nairobi"
  },
  {
    id: 36,
    title: "One Night Only",
    posterUrl: "https://image.tmdb.org/t/p/w500/gzy1L7wqkFRznQPv4WrdPQ9bCJ8.jpg",
    publicReleaseDate: "2026-08-07",
    description: "A romantic comedy about two people forced into one chaotic night that keeps rewriting their plans.",
    director: "Will Gluck",
    worldPremiere: "2026-08-02 — Regency Village Theatre, Los Angeles",
    categories: ["Comedy", "Romance"],
    mainCast: ["Monica Barbaro", "Callum Turner", "Maya Hawke", "Molly Ringwald"],
    runtime: "104 min",
    releaseVenue: "Century Cinemax Two Rivers, Nairobi"
  },
  {
    id: 37,
    title: "Super Troopers 3",
    posterUrl: "https://image.tmdb.org/t/p/w500/eV2Uhn8A93V4ELySlrBGvBuQJLj.jpg",
    publicReleaseDate: "2026-08-07",
    description: "The Broken Lizard comedy team returns for another round of absurd police misadventures.",
    director: "Jay Chandrasekhar",
    worldPremiere: "2026-08-01 — Austin Comedy Film Night",
    categories: ["Comedy"],
    mainCast: ["Jay Chandrasekhar", "Kevin Heffernan", "Steve Lemme", "Brian Cox"],
    runtime: "103 min",
    releaseVenue: "Prestige Cinema, Nairobi"
  },
  {
    id: 38,
    title: "CatVideoFest 2026",
    posterUrl: "https://image.tmdb.org/t/p/w500/nRjejxXF7tV8nZ8RFrHyOswuCle.jpg",
    publicReleaseDate: "2026-08-07",
    description: "A curated cinema event collecting funny, strange, and charming cat videos for a communal theatrical screening.",
    director: "Will Braden",
    worldPremiere: "2026-08-04 — Walker Art Center, Minneapolis",
    categories: ["Documentary", "Comedy", "Family"],
    mainCast: ["Featured cats", "CatVideoFest audience community"],
    runtime: "73 min",
    releaseVenue: "Unseen Nairobi Rooftop Cinema"
  },
  {
    id: 39,
    title: "Cookie Queens",
    posterUrl: "https://image.tmdb.org/t/p/w500/lrb4Toi6BJHWwOz9clh1aJGJDj8.jpg",
    publicReleaseDate: "2026-08-07",
    description: "A warm comedy about rival bakers whose competition becomes a test of friendship, family, and ambition.",
    director: "Nisha Ganatra",
    worldPremiere: "2026-08-02 — Toronto Summer Audience Preview",
    categories: ["Comedy", "Family"],
    mainCast: ["Cast TBA"],
    runtime: "98 min",
    releaseVenue: "Century Cinemax Junction, Nairobi"
  },
  {
    id: 40,
    title: "Julian",
    posterUrl: "https://image.tmdb.org/t/p/w500/l9pizBjOcP29Di6gO2ttgED3bVe.jpg",
    publicReleaseDate: "2026-08-07",
    description: "A character drama about a young person rebuilding confidence after a public mistake changes their future.",
    director: "Ciro Guerra",
    worldPremiere: "2026-08-01 — Cartagena Special Screening",
    categories: ["Drama"],
    mainCast: ["Cast TBA"],
    runtime: "106 min",
    releaseVenue: "Alliance Française de Nairobi"
  },
  {
    id: 41,
    title: "Late Fame",
    posterUrl: "https://image.tmdb.org/t/p/w500/bcyXE0p4XmZUlcxvTDbvdG9lgsN.jpg",
    publicReleaseDate: "2026-08-07",
    description: "A literary drama about an overlooked writer who receives attention long after the moment he expected it.",
    director: "Kent Jones",
    worldPremiere: "2026-08-03 — New York Film Festival Summer Preview",
    categories: ["Drama"],
    mainCast: ["Willem Dafoe", "Greta Lee", "Edmund Donovan"],
    runtime: "108 min",
    releaseVenue: "Nairobi Film Centre"
  },
  {
    id: 42,
    title: "Olmo",
    posterUrl: "https://image.tmdb.org/t/p/w500/qQ6mkgs2JIDMj8Av6vzuRgWQNrm.jpg",
    publicReleaseDate: "2026-08-07",
    description: "A coming-of-age drama centered on a boy navigating family tension, memory, and a summer that changes him.",
    director: "Fernando Eimbcke",
    worldPremiere: "2026-08-01 — Morelia Preview Screening",
    categories: ["Drama", "Coming-of-age"],
    mainCast: ["Gustavo Sánchez Parra", "Aivan Uttapa", "Diego Olmedo", "Andrea Suárez Paz"],
    runtime: "99 min",
    releaseVenue: "Alliance Française de Nairobi"
  },
  {
    id: 43,
    title: "Tony",
    posterUrl: "https://image.tmdb.org/t/p/w500/zFBRMVDgKRZ6dqTZwkefBbfDC1G.jpg",
    publicReleaseDate: "2026-08-07",
    description: "A sharp character comedy-drama about image, reinvention, and the unstable mythology around a public figure.",
    director: "Matt Johnson",
    worldPremiere: "2026-08-04 — A24 Brooklyn Preview",
    categories: ["Comedy", "Drama"],
    mainCast: ["Dominic Sessa", "Emilia Jones", "Dagmara Domińczyk", "Antonio Banderas"],
    runtime: "111 min",
    releaseVenue: "Anga Diamond Plaza, Nairobi"
  },
  {
    id: 44,
    title: "The Brink of War",
    posterUrl: "https://image.tmdb.org/t/p/w500/ubVMXPp9OmLjET8NYbZZHQCFMcx.jpg",
    publicReleaseDate: "2026-08-14",
    description: "A political historical drama focused on leaders facing a crisis that could push the world into conflict.",
    director: "Michael Russell Gunn",
    worldPremiere: "2026-08-09 — Washington D.C. Historical Cinema Gala",
    categories: ["Drama", "History", "Political"],
    mainCast: ["Jeff Daniels", "Jared Harris", "J. K. Simmons", "Hope Davis"],
    runtime: "128 min",
    releaseVenue: "Century Cinemax Sarit, Nairobi"
  },
  {
    id: 45,
    title: "The End of Oak Street",
    posterUrl: "https://image.tmdb.org/t/p/w500/3AJff1foTrXplV687A1NAMw7nV4.jpg",
    publicReleaseDate: "2026-08-14",
    description: "A sci-fi mystery about a suburban street where reality begins to bend around one impossible event.",
    director: "David Robert Mitchell",
    worldPremiere: "2026-08-10 — TCL Chinese Theatre, Hollywood",
    categories: ["Sci-Fi", "Mystery", "Drama"],
    mainCast: ["Anne Hathaway", "Ewan McGregor", "Maisy Stella", "Christian Convery"],
    runtime: "119 min",
    releaseVenue: "IMAX Garden City, Nairobi"
  },
  {
    id: 46,
    title: "PAW Patrol: The Dino Movie",
    posterUrl: "https://image.tmdb.org/t/p/w500/aLVkiINlIeCkcZIzb7XHzPYgO6L.jpg",
    publicReleaseDate: "2026-08-14",
    description: "The PAW Patrol team heads into a dinosaur-themed adventure built for young family audiences.",
    director: "Cal Brunker",
    worldPremiere: "2026-08-09 — Toronto Family Film Premiere",
    categories: ["Animation", "Adventure", "Family"],
    mainCast: ["McKenna Grace", "Jennifer Hudson", "Fortune Feimster"],
    runtime: "92 min",
    releaseVenue: "Century Cinemax Two Rivers, Nairobi"
  },
  {
    id: 47,
    title: "The Rivals of Amziah King",
    posterUrl: "https://image.tmdb.org/t/p/w500/zKVgiv5qHCvCLT4A2ymJi5QeXDH.jpg",
    publicReleaseDate: "2026-08-14",
    description: "A crime-tinged Southern drama about a charismatic figure, old grudges, and a community built on secrets.",
    director: "Andrew Patterson",
    worldPremiere: "2026-08-08 — Telluride Early Access Screening",
    categories: ["Crime", "Drama"],
    mainCast: ["Matthew McConaughey", "Kurt Russell", "Rob Morgan", "Tony Revolori"],
    runtime: "116 min",
    releaseVenue: "Prestige Cinema, Nairobi"
  },
  {
    id: 48,
    title: "The Wrong Girls",
    posterUrl: "https://image.tmdb.org/t/p/w500/3AJff1foTrXplV687A1NAMw7nV4.jpg",
    publicReleaseDate: "2026-08-14",
    description: "A chaotic comedy about a group of women pulled into the wrong situation at exactly the wrong time.",
    director: "Dylan Meyer",
    worldPremiere: "2026-08-07 — Los Angeles Comedy Works Preview",
    categories: ["Comedy"],
    mainCast: ["Kristen Stewart", "Alia Shawkat", "Seth Rogen", "LaKeith Stanfield"],
    runtime: "102 min",
    releaseVenue: "Unseen Nairobi Rooftop Cinema"
  },
  {
    id: 49,
    title: "Nimrods",
    posterUrl: "https://image.tmdb.org/t/p/w500/zKVgiv5qHCvCLT4A2ymJi5QeXDH.jpg",
    publicReleaseDate: "2026-08-14",
    description: "A music-inflected comedy about misfits, local fame, and the messy energy around a band’s second chance.",
    director: "Lee Kirk",
    worldPremiere: "2026-08-08 — Chicago Music Box Theatre",
    categories: ["Comedy", "Music"],
    mainCast: ["Mason Thames", "Mckenna Grace", "Jenna Fischer", "Fred Armisen"],
    runtime: "100 min",
    releaseVenue: "Anga Diamond Plaza, Nairobi"
  },
  {
    id: 50,
    title: "Union County",
    posterUrl: "https://image.tmdb.org/t/p/w500/aLVkiINlIeCkcZIzb7XHzPYgO6L.jpg",
    publicReleaseDate: "2026-08-14",
    description: "An intimate drama-thriller about loyalty, class pressure, and a decision that divides a small community.",
    director: "Adam Meeks",
    worldPremiere: "2026-08-06 — Nashville Independent Film Preview",
    categories: ["Drama", "Thriller"],
    mainCast: ["Will Poulter", "Noah Centineo", "Elise Kibler", "Emily Meade"],
    runtime: "105 min",
    releaseVenue: "Nairobi Film Centre"
  },
  {
    id: 51,
    title: "Battle Of Galwan",
    posterUrl: "https://image.tmdb.org/t/p/w500/3AJff1foTrXplV687A1NAMw7nV4.jpg",
    publicReleaseDate: "2026-08-15",
    description: "A military drama centered on courage, strategy, and sacrifice during a tense border confrontation.",
    director: "TBA",
    worldPremiere: "2026-08-11 — Mumbai Military Cinema Gala",
    categories: ["Action", "Drama", "War"],
    mainCast: ["Cast TBA"],
    runtime: "132 min",
    releaseVenue: "Century Cinemax Sarit, Nairobi"
  },
  {
    id: 52,
    title: "Hot Spot",
    posterUrl: "https://image.tmdb.org/t/p/w500/kiFacg75KVjy0AM3S4QmbPas8zL.jpg",
    publicReleaseDate: "2026-08-21",
    description: "A tense crime thriller set around a location where one mistake can expose an entire operation.",
    director: "TBA",
    worldPremiere: "2026-08-17 — Toronto Midnight Preview",
    categories: ["Crime", "Thriller", "Drama"],
    mainCast: ["Cast TBA"],
    runtime: "104 min",
    releaseVenue: "Anga Diamond Plaza, Nairobi"
  },
  {
    id: 53,
    title: "Insidious: Out of the Further",
    posterUrl: "https://image.tmdb.org/t/p/w500/aLVkiINlIeCkcZIzb7XHzPYgO6L.jpg",
    publicReleaseDate: "2026-08-21",
    description: "A supernatural horror entry exploring another case connected to the dark realm known as the Further.",
    director: "TBA",
    worldPremiere: "2026-08-18 — TCL Chinese Theatre, Hollywood",
    categories: ["Horror", "Supernatural", "Thriller"],
    mainCast: ["Cast TBA"],
    runtime: "103 min",
    releaseVenue: "Anga CBD, Nairobi"
  },
  {
    id: 54,
    title: "Mutiny",
    posterUrl: "https://image.tmdb.org/t/p/w500/7zNmJP6z6mDAp4LouacYkGSBUQv.jpg",
    publicReleaseDate: "2026-08-21",
    description: "An action thriller about betrayal inside a dangerous mission where command collapses from within.",
    director: "TBA",
    worldPremiere: "2026-08-16 — London Action Cinema Showcase",
    categories: ["Action", "Thriller"],
    mainCast: ["Cast TBA"],
    runtime: "111 min",
    releaseVenue: "Century Cinemax Garden City, Nairobi"
  },
  {
    id: 55,
    title: "Spa Weekend",
    posterUrl: "https://image.tmdb.org/t/p/w500/3AJff1foTrXplV687A1NAMw7nV4.jpg",
    publicReleaseDate: "2026-08-21",
    description: "A social comedy about a luxury retreat where relaxation turns into rivalry, secrets, and awkward honesty.",
    director: "TBA",
    worldPremiere: "2026-08-15 — Palm Springs Comedy Preview",
    categories: ["Comedy", "Drama"],
    mainCast: ["Cast TBA"],
    runtime: "98 min",
    releaseVenue: "Prestige Cinema, Nairobi"
  },
  {
    id: 56,
    title: "Untitled Vertical Family Movie",
    posterUrl: "https://image.tmdb.org/t/p/w500/3AJff1foTrXplV687A1NAMw7nV4.jpg",
    publicReleaseDate: "2026-08-21",
    description: "A family-friendly adventure about siblings who learn responsibility while trying to save their summer plans.",
    director: "TBA",
    worldPremiere: "2026-08-18 — Atlanta Family Film Night",
    categories: ["Family", "Adventure", "Comedy"],
    mainCast: ["Cast TBA"],
    runtime: "94 min",
    releaseVenue: "Century Cinemax Two Rivers, Nairobi"
  },
  {
    id: 57,
    title: "The Magic Faraway Tree",
    posterUrl: "https://image.tmdb.org/t/p/w500/udXvLxC5gAqN8SinemyFBEcHpTf.jpg",
    publicReleaseDate: "2026-08-21",
    description: "A fantasy adventure about children discovering an enchanted tree that leads to strange and changing worlds.",
    director: "TBA",
    worldPremiere: "2026-08-14 — BFI Family Gala, London",
    categories: ["Fantasy", "Family", "Adventure"],
    mainCast: ["Cast TBA"],
    runtime: "108 min",
    releaseVenue: "Century Cinemax Junction, Nairobi"
  },
  {
    id: 58,
    title: "The Marching Band",
    posterUrl: "https://image.tmdb.org/t/p/w500/6lATJ42bWGAIQ0cG2dzSZD8bNcL.jpg",
    publicReleaseDate: "2026-08-21",
    description: "A music-driven drama about discipline, friendship, and the pressure of preparing for a major performance.",
    director: "TBA",
    worldPremiere: "2026-08-13 — Paris Music Film Preview",
    categories: ["Drama", "Music"],
    mainCast: ["Cast TBA"],
    runtime: "103 min",
    releaseVenue: "Alliance Française de Nairobi"
  },
  {
    id: 59,
    title: "Paper Flowers",
    posterUrl: "https://image.tmdb.org/t/p/w500/nPH0ZhR1L4PUafhoqfipHj1gTg.jpg",
    publicReleaseDate: "2026-08-21",
    description: "A gentle drama about memory, grief, and a handmade gift that connects two families across time.",
    director: "TBA",
    worldPremiere: "2026-08-12 — Telluride Early Preview",
    categories: ["Drama", "Romance"],
    mainCast: ["Cast TBA"],
    runtime: "100 min",
    releaseVenue: "Nairobi Film Centre"
  },
  {
    id: 60,
    title: "Castle in the Sky",
    posterUrl: "https://image.tmdb.org/t/p/w500/41XxSsJc5OrulP0m7TrrUeO2hoz.jpg",
    publicReleaseDate: "2026-08-22",
    description: "A theatrical re-release of the animated fantasy adventure about a floating kingdom and two children pursued by powerful forces.",
    director: "Hayao Miyazaki",
    worldPremiere: "1986-08-02 — Japan Theatrical Premiere",
    categories: ["Animation", "Adventure", "Fantasy"],
    mainCast: ["Mayumi Tanaka", "Keiko Yokozawa", "Kotoe Hatsui"],
    runtime: "124 min",
    releaseVenue: "Unseen Nairobi Rooftop Cinema"
  },
  {
    id: 61,
    title: "Buddy",
    posterUrl: "https://image.tmdb.org/t/p/w500/qjRWZ1Ak9Ag6EvcA5LNhphqX8oV.jpg",
    publicReleaseDate: "2026-08-28",
    description: "A feel-good comedy about an unlikely friendship that pushes two very different people into the same chaotic journey.",
    director: "TBA",
    worldPremiere: "2026-08-24 — Los Angeles Family Comedy Preview",
    categories: ["Comedy", "Family"],
    mainCast: ["Cast TBA"],
    runtime: "101 min",
    releaseVenue: "Century Cinemax Two Rivers, Nairobi"
  },
  {
    id: 62,
    title: "Cliffhanger",
    posterUrl: "https://image.tmdb.org/t/p/w500/b28DOM54OHb1c7Lsk6Nu7Kwuonj.jpg",
    publicReleaseDate: "2026-08-28",
    description: "A high-altitude action thriller built around survival, pursuit, and danger in extreme mountain terrain.",
    director: "TBA",
    worldPremiere: "2026-08-23 — Dolomites Action Film Gala",
    categories: ["Action", "Adventure", "Thriller"],
    mainCast: ["Cast TBA"],
    runtime: "113 min",
    releaseVenue: "IMAX Garden City, Nairobi"
  },
  {
    id: 63,
    title: "Coyote vs. Acme",
    posterUrl: "https://image.tmdb.org/t/p/w500/7zNmJP6z6mDAp4LouacYkGSBUQv.jpg",
    publicReleaseDate: "2026-08-28",
    description: "Wile E. Coyote takes Acme to court after years of failed gadgets, turning cartoon chaos into a legal comedy.",
    director: "Dave Green",
    worldPremiere: "2026-08-22 — Warner Bros. Studio Lot, Burbank",
    categories: ["Animation", "Comedy", "Family"],
    mainCast: ["Will Forte", "John Cena", "Lana Condor"],
    runtime: "98 min",
    releaseVenue: "Century Cinemax Sarit, Nairobi"
  },
  {
    id: 64,
    title: "The Dog Stars",
    posterUrl: "https://image.tmdb.org/t/p/w500/A7i16oDi03qrKep5pBfuTWNUTb.jpg",
    publicReleaseDate: "2026-08-28",
    description: "A post-apocalyptic drama about a pilot searching for connection and hope after civilization has been reshaped.",
    director: "Ridley Scott",
    worldPremiere: "2026-08-20 — Venice Out of Competition Gala",
    categories: ["Drama", "Sci-Fi", "Adventure"],
    mainCast: ["Cast TBA"],
    runtime: "126 min",
    releaseVenue: "IMAX Garden City, Nairobi"
  },
  {
    id: 65,
    title: "Finding Emily",
    posterUrl: "https://image.tmdb.org/t/p/w500/bfEQ6C702oPsN4kzIiY7n4JsrxF.jpg",
    publicReleaseDate: "2026-08-28",
    description: "A personal drama about a search that forces a family to confront the truth behind a long silence.",
    director: "TBA",
    worldPremiere: "2026-08-21 — Sundance Summer Selection",
    categories: ["Drama", "Mystery"],
    mainCast: ["Cast TBA"],
    runtime: "107 min",
    releaseVenue: "Nairobi Film Centre"
  },
  {
    id: 66,
    title: "Idiots",
    posterUrl: "https://image.tmdb.org/t/p/w500/66A9MqXOyVFCssoloscw79z8Tew.jpg",
    publicReleaseDate: "2026-08-28",
    description: "A sharp ensemble comedy about friends whose bad decisions spiral into one extremely public disaster.",
    director: "TBA",
    worldPremiere: "2026-08-20 — Austin Comedy Film Preview",
    categories: ["Comedy"],
    mainCast: ["Cast TBA"],
    runtime: "96 min",
    releaseVenue: "Anga Diamond Plaza, Nairobi"
  },
  {
    id: 67,
    title: "Beyond Belief",
    posterUrl: "https://image.tmdb.org/t/p/w500/x6t4LPGYdCLqsdijZqSOxzic3Tj.jpg",
    publicReleaseDate: "2026-08-28",
    description: "A documentary-style mystery about faith, skepticism, and stories that resist easy explanation.",
    director: "TBA",
    worldPremiere: "2026-08-19 — Denver Documentary Preview",
    categories: ["Documentary", "Mystery"],
    mainCast: ["Featured participants TBA"],
    runtime: "89 min",
    releaseVenue: "Alliance Française de Nairobi"
  },
  {
    id: 68,
    title: "Colony",
    posterUrl: "https://image.tmdb.org/t/p/w500/qfS0mp22XfTig2EK3jWKiyx7kNy.jpg",
    publicReleaseDate: "2026-08-28",
    description: "A sci-fi survival thriller set inside an isolated settlement where the rules begin to fail.",
    director: "TBA",
    worldPremiere: "2026-08-22 — Seoul Sci-Fi Showcase",
    categories: ["Sci-Fi", "Thriller"],
    mainCast: ["Cast TBA"],
    runtime: "105 min",
    releaseVenue: "Century Cinemax Garden City, Nairobi"
  },
  {
    id: 69,
    title: "Filipiñana",
    posterUrl: "https://image.tmdb.org/t/p/w500/64hnrTmeJEvUYoJyuOM7taE3CqT.jpg",
    publicReleaseDate: "2026-08-28",
    description: "A social drama set around work, class, and quiet rebellion inside a controlled private world.",
    director: "Rafael Manuel",
    worldPremiere: "2026-08-18 — Manila Independent Film Gala",
    categories: ["Drama", "Social Realism"],
    mainCast: ["Cast TBA"],
    runtime: "95 min",
    releaseVenue: "Unseen Nairobi Rooftop Cinema"
  },
  {
    id: 70,
    title: "Legend of the White Dragon",
    posterUrl: "https://image.tmdb.org/t/p/w500/kaMEYF6bMuOO3z504EIm7P1zprT.jpg",
    publicReleaseDate: "2026-08-28",
    description: "A superhero action film about a fallen protector returning to face enemies from his past.",
    director: "Aaron Schoenke",
    worldPremiere: "2026-08-23 — Los Angeles Action Fan Event",
    categories: ["Action", "Fantasy", "Superhero"],
    mainCast: ["Jason David Frank", "Aaron Schoenke", "Ciara Hanna"],
    runtime: "93 min",
    releaseVenue: "Century Cinemax Sarit, Nairobi"
  },
  {
    id: 71,
    title: "Fall 2: Deadpoint",
    posterUrl: "https://image.tmdb.org/t/p/w500/ckKAdEz49bJ10jCLbCYIzVHJGEu.jpg",
    publicReleaseDate: "2026-09-02",
    description: "A survival thriller about climbers trapped in a place where rescue is nearly impossible.",
    director: "TBA",
    worldPremiere: "2026-08-29 — Las Vegas Extreme Cinema Night",
    categories: ["Adventure", "Thriller", "Survival"],
    mainCast: ["Cast TBA"],
    runtime: "102 min",
    releaseVenue: "Anga Diamond Plaza, Nairobi"
  },
  {
    id: 72,
    title: "By Any Means",
    posterUrl: "https://image.tmdb.org/t/p/w500/kiFacg75KVjy0AM3S4QmbPas8zL.jpg",
    publicReleaseDate: "2026-09-04",
    description: "A crime thriller about a determined investigator willing to cross lines to expose a dangerous network.",
    director: "TBA",
    worldPremiere: "2026-08-31 — New York Crime Cinema Preview",
    categories: ["Crime", "Thriller", "Drama"],
    mainCast: ["Cast TBA"],
    runtime: "110 min",
    releaseVenue: "Prestige Cinema, Nairobi"
  },
  {
    id: 73,
    title: "Cocoon: One Summer of Girlhood",
    posterUrl: "https://image.tmdb.org/t/p/w500/aLVkiINlIeCkcZIzb7XHzPYgO6L.jpg",
    publicReleaseDate: "2026-09-04",
    description: "A coming-of-age animated drama about friendship, identity, and the emotional intensity of one summer.",
    director: "TBA",
    worldPremiere: "2026-08-27 — Annecy Encore Screening",
    categories: ["Animation", "Drama", "Coming-of-age"],
    mainCast: ["Voice cast TBA"],
    runtime: "91 min",
    releaseVenue: "Alliance Française de Nairobi"
  },
  {
    id: 74,
    title: "How to Rob a Bank",
    posterUrl: "https://image.tmdb.org/t/p/w500/kiFacg75KVjy0AM3S4QmbPas8zL.jpg",
    publicReleaseDate: "2026-09-04",
    description: "A heist comedy-thriller about a group with a reckless plan and almost no margin for error.",
    director: "TBA",
    worldPremiere: "2026-08-30 — Toronto Midnight Madness Preview",
    categories: ["Crime", "Comedy", "Thriller"],
    mainCast: ["Cast TBA"],
    runtime: "106 min",
    releaseVenue: "Century Cinemax Junction, Nairobi"
  },
  {
    id: 75,
    title: "Onslaught",
    posterUrl: "https://image.tmdb.org/t/p/w500/aLVkiINlIeCkcZIzb7XHzPYgO6L.jpg",
    publicReleaseDate: "2026-09-04",
    description: "An action-horror film about a sudden violent threat that forces ordinary people into survival mode.",
    director: "Adam Wingard",
    worldPremiere: "2026-08-29 — Fantastic Fest Opening Preview",
    categories: ["Action", "Horror", "Thriller"],
    mainCast: ["Cast TBA"],
    runtime: "109 min",
    releaseVenue: "Anga CBD, Nairobi"
  },
  {
    id: 76,
    title: "Barbara Forever",
    posterUrl: "https://image.tmdb.org/t/p/w500/7zNmJP6z6mDAp4LouacYkGSBUQv.jpg",
    publicReleaseDate: "2026-09-04",
    description: "A reflective drama about legacy, memory, and a woman whose influence remains after she is gone.",
    director: "TBA",
    worldPremiere: "2026-08-25 — Venice Horizons Preview",
    categories: ["Drama"],
    mainCast: ["Cast TBA"],
    runtime: "97 min",
    releaseVenue: "Nairobi Film Centre"
  },
  {
    id: 77,
    title: "Tom and Jerry: Forbidden Compass",
    posterUrl: "https://image.tmdb.org/t/p/w500/7zNmJP6z6mDAp4LouacYkGSBUQv.jpg",
    publicReleaseDate: "2026-09-09",
    description: "Tom and Jerry stumble into a globe-trotting adventure involving a mysterious compass and a race across landmarks.",
    director: "TBA",
    worldPremiere: "2026-09-05 — Warner Bros. Family Premiere, Los Angeles",
    categories: ["Animation", "Comedy", "Family"],
    mainCast: ["Voice cast TBA"],
    runtime: "88 min",
    releaseVenue: "Century Cinemax Two Rivers, Nairobi"
  },
  {
    id: 78,
    title: "Daniel: The Fiery Furnace",
    posterUrl: "https://image.tmdb.org/t/p/w500/aLVkiINlIeCkcZIzb7XHzPYgO6L.jpg",
    publicReleaseDate: "2026-09-11",
    description: "A faith-based historical drama retelling a story of courage, conviction, and survival under pressure.",
    director: "TBA",
    worldPremiere: "2026-09-07 — Dallas Faith Film Premiere",
    categories: ["Drama", "History", "Faith"],
    mainCast: ["Cast TBA"],
    runtime: "118 min",
    releaseVenue: "Century Cinemax Sarit, Nairobi"
  },
  {
    id: 79,
    title: "The Fix",
    posterUrl: "https://image.tmdb.org/t/p/w500/7zNmJP6z6mDAp4LouacYkGSBUQv.jpg",
    publicReleaseDate: "2026-09-11",
    description: "A thriller about a professional problem-solver whose latest assignment becomes impossible to control.",
    director: "TBA",
    worldPremiere: "2026-09-06 — Los Angeles Thriller Showcase",
    categories: ["Thriller", "Crime"],
    mainCast: ["Cast TBA"],
    runtime: "103 min",
    releaseVenue: "Anga Diamond Plaza, Nairobi"
  },
  {
    id: 80,
    title: "Oasis Live ‘25",
    posterUrl: "https://image.tmdb.org/t/p/w500/zKVgiv5qHCvCLT4A2ymJi5QeXDH.jpg",
    publicReleaseDate: "2026-09-11",
    description: "A concert-film event capturing the scale, energy, and audience reaction of Oasis performing live.",
    director: "TBA",
    worldPremiere: "2026-09-08 — London Event Cinema Premiere",
    categories: ["Music", "Concert", "Documentary"],
    mainCast: ["Oasis"],
    runtime: "112 min",
    releaseVenue: "Anga Diamond Plaza, Nairobi"
  },
  {
    id: 81,
    title: "Practical Magic 2",
    posterUrl: "https://image.tmdb.org/t/p/w500/7zNmJP6z6mDAp4LouacYkGSBUQv.jpg",
    publicReleaseDate: "2026-09-11",
    description: "A sequel to the supernatural romance-drama about family, magic, and the complicated inheritance of love.",
    director: "Susanne Bier",
    worldPremiere: "2026-09-07 — Regency Village Theatre, Los Angeles",
    categories: ["Fantasy", "Romance", "Drama"],
    mainCast: ["Sandra Bullock", "Nicole Kidman"],
    runtime: "116 min",
    releaseVenue: "Century Cinemax Garden City, Nairobi"
  },
  {
    id: 82,
    title: "Runner",
    posterUrl: "https://image.tmdb.org/t/p/w500/7zNmJP6z6mDAp4LouacYkGSBUQv.jpg",
    publicReleaseDate: "2026-09-11",
    description: "A propulsive action drama about a courier pulled into a dangerous chase across a locked-down city.",
    director: "TBA",
    worldPremiere: "2026-09-05 — Chicago Action Film Preview",
    categories: ["Action", "Drama", "Thriller"],
    mainCast: ["Cast TBA"],
    runtime: "101 min",
    releaseVenue: "Prestige Cinema, Nairobi"
  },
  {
    id: 83,
    title: "Untitled Neon Film",
    posterUrl: "https://image.tmdb.org/t/p/w500/3AJff1foTrXplV687A1NAMw7nV4.jpg",
    publicReleaseDate: "2026-09-11",
    description: "A prestige mystery-drama release with final title and campaign materials still pending.",
    director: "TBA",
    worldPremiere: "2026-09-04 — Toronto Special Presentation",
    categories: ["Drama", "Mystery"],
    mainCast: ["Cast TBA"],
    runtime: "100 min",
    releaseVenue: "Nairobi Film Centre"
  },
  {
    id: 84,
    title: "The Uprising",
    posterUrl: "https://image.tmdb.org/t/p/w500/zKVgiv5qHCvCLT4A2ymJi5QeXDH.jpg",
    publicReleaseDate: "2026-09-11",
    description: "A historical action-drama about ordinary people organizing against an overwhelming authority.",
    director: "TBA",
    worldPremiere: "2026-09-03 — Toronto Historical Cinema Gala",
    categories: ["Action", "Drama", "History"],
    mainCast: ["Cast TBA"],
    runtime: "127 min",
    releaseVenue: "Century Cinemax Sarit, Nairobi"
  },
  {
    id: 85,
    title: "Black Zombie",
    posterUrl: "https://image.tmdb.org/t/p/w500/aLVkiINlIeCkcZIzb7XHzPYgO6L.jpg",
    publicReleaseDate: "2026-09-11",
    description: "A restored genre release bringing a vintage horror title back to theaters for specialty audiences.",
    director: "Jean Yarbrough",
    worldPremiere: "1943-05-21 — Original U.S. Theatrical Release",
    categories: ["Horror", "Classic", "Re-release"],
    mainCast: ["Mantan Moreland", "John Carradine", "Gale Storm"],
    runtime: "69 min",
    releaseVenue: "Unseen Nairobi Rooftop Cinema"
  },
  {
    id: 86,
    title: "The Transformers: The Movie",
    posterUrl: "https://image.tmdb.org/t/p/w500/xJ5W0mOAWCVaXmU0pBZh4NjSRv2.jpg",
    publicReleaseDate: "2026-09-17",
    description: "A theatrical re-release of the animated Transformers adventure featuring Autobots, Decepticons, and a planet-sized threat.",
    director: "Nelson Shin",
    worldPremiere: "1986-08-08 — Original U.S. Theatrical Release",
    categories: ["Animation", "Action", "Sci-Fi", "Re-release"],
    mainCast: ["Peter Cullen", "Judd Nelson", "Leonard Nimoy"],
    runtime: "84 min",
    releaseVenue: "Century Cinemax Garden City, Nairobi"
  },
  {
    id: 87,
    title: "Resident Evil",
    posterUrl: "https://image.tmdb.org/t/p/w500/rmLvn4w4HMdxobPkjmIqrhJiXDO.jpg",
    publicReleaseDate: "2026-09-18",
    description: "A new theatrical Resident Evil film returning the survival-horror franchise to a dangerous outbreak scenario.",
    director: "Zach Cregger",
    worldPremiere: "2026-09-14 — Sony Pictures Lot, Culver City",
    categories: ["Horror", "Action", "Sci-Fi"],
    mainCast: ["Cast TBA"],
    runtime: "107 min",
    releaseVenue: "IMAX Garden City, Nairobi"
  },
  {
    id: 88,
    title: "Shaun the Sheep: The Beast of Mossy Bottom",
    posterUrl: "https://image.tmdb.org/t/p/w500/mMOptSPBVGUA9GHgnpsC35GzZ7e.jpg",
    publicReleaseDate: "2026-09-18",
    description: "Shaun and the flock face a strange new mystery in a playful stop-motion adventure from Mossy Bottom Farm.",
    director: "TBA",
    worldPremiere: "2026-09-12 — Bristol Animation Gala",
    categories: ["Animation", "Family", "Comedy"],
    mainCast: ["Voice cast TBA"],
    runtime: "87 min",
    releaseVenue: "Century Cinemax Two Rivers, Nairobi"
  },
  {
    id: 89,
    title: "The Weight",
    posterUrl: "https://image.tmdb.org/t/p/w500/lGrf2U5mu06WjXBCwCjbTGEjscp.jpg",
    publicReleaseDate: "2026-09-18",
    description: "A drama-thriller about guilt, responsibility, and the burden of one decision that cannot be undone.",
    director: "TBA",
    worldPremiere: "2026-09-10 — Venice Critics’ Week Preview",
    categories: ["Drama", "Thriller"],
    mainCast: ["Cast TBA"],
    runtime: "105 min",
    releaseVenue: "Nairobi Film Centre"
  },
  {
    id: 90,
    title: "Avengers: Endgame",
    posterUrl: "https://image.tmdb.org/t/p/w500/ulzhLuWrPK07P1YkdWQLZnQh1JL.jpg",
    publicReleaseDate: "2026-09-25",
    description: "A theatrical re-release of Marvel’s ensemble finale about the Avengers’ final attempt to reverse a cosmic defeat.",
    director: "Anthony Russo, Joe Russo",
    worldPremiere: "2019-04-22 — Los Angeles Convention Center",
    categories: ["Action", "Adventure", "Superhero", "Re-release"],
    mainCast: ["Robert Downey Jr.", "Chris Evans", "Scarlett Johansson", "Chris Hemsworth"],
    runtime: "181 min",
    releaseVenue: "IMAX Garden City, Nairobi"
  },
  {
    id: 91,
    title: "Charlie Harper",
    posterUrl: "https://image.tmdb.org/t/p/w500/jvAhbwqkbqexBacuu66NSixvAj7.jpg",
    publicReleaseDate: "2026-09-25",
    description: "A character-driven drama about fame, personal reinvention, and the cost of being misunderstood.",
    director: "TBA",
    worldPremiere: "2026-09-18 — New York Fall Film Preview",
    categories: ["Drama", "Comedy"],
    mainCast: ["Cast TBA"],
    runtime: "102 min",
    releaseVenue: "Prestige Cinema, Nairobi"
  },
  {
    id: 92,
    title: "Forgotten Island",
    posterUrl: "https://image.tmdb.org/t/p/w500/kW1fH2jZZM5tVHwNaDdUOUXJvWU.jpg",
    publicReleaseDate: "2026-09-25",
    description: "A mystery-adventure about a remote island whose past becomes impossible to ignore.",
    director: "TBA",
    worldPremiere: "2026-09-19 — Vancouver Adventure Cinema Night",
    categories: ["Adventure", "Mystery", "Drama"],
    mainCast: ["Cast TBA"],
    runtime: "115 min",
    releaseVenue: "Century Cinemax Sarit, Nairobi"
  },
  {
    id: 93,
    title: "Heart of the Beast",
    posterUrl: "https://image.tmdb.org/t/p/w500/1ApfSA8JTqeha3GTFEY8syV4auq.jpg",
    publicReleaseDate: "2026-09-25",
    description: "An action-adventure drama about survival, loyalty, and an unlikely bond formed under extreme pressure.",
    director: "David Ayer",
    worldPremiere: "2026-09-20 — Los Angeles Action Gala",
    categories: ["Action", "Adventure", "Drama"],
    mainCast: ["Cast TBA"],
    runtime: "118 min",
    releaseVenue: "Century Cinemax Garden City, Nairobi"
  },
  {
    id: 94,
    title: "Victorian Psycho",
    posterUrl: "https://image.tmdb.org/t/p/w500/dZ25ve1QeX0JliOh24kqevZzKFi.jpg",
    publicReleaseDate: "2026-09-25",
    description: "A gothic psychological thriller set in a rigid household where appearances hide something deeply unstable.",
    director: "Zachary Wigon",
    worldPremiere: "2026-09-15 — Fantastic Fest Gothic Preview",
    categories: ["Thriller", "Gothic", "Drama"],
    mainCast: ["Cast TBA"],
    runtime: "104 min",
    releaseVenue: "Anga CBD, Nairobi"
  },
  {
    id: 95,
    title: "April X",
    posterUrl: "https://image.tmdb.org/t/p/w500/6kAlyJGzXTTbeqDWQlMqc1HE9ew.jpg",
    publicReleaseDate: "2026-09-25",
    description: "A stylish independent drama about identity, reinvention, and a woman staging her own disappearance.",
    director: "TBA",
    worldPremiere: "2026-09-17 — San Sebastián New Directors Preview",
    categories: ["Drama", "Mystery"],
    mainCast: ["Cast TBA"],
    runtime: "96 min",
    releaseVenue: "Alliance Française de Nairobi"
  },
  {
    id: 96,
    title: "Deep In The Heart 2: A Texas Rivers Story",
    posterUrl: "https://image.tmdb.org/t/p/w500/zKVgiv5qHCvCLT4A2ymJi5QeXDH.jpg",
    publicReleaseDate: "2026-09-25",
    description: "A nature documentary exploring river ecosystems, conservation work, and the landscapes shaped by water.",
    director: "TBA",
    worldPremiere: "2026-09-16 — Austin Nature Film Forum",
    categories: ["Documentary", "Nature"],
    mainCast: ["Featured conservationists TBA"],
    runtime: "86 min",
    releaseVenue: "Nairobi National Museum Auditorium"
  },
  {
    id: 97,
    title: "Never After Dark",
    posterUrl: "https://image.tmdb.org/t/p/w500/4rDgzOCBREeTaqZvTeFtEcnrju8.jpg",
    publicReleaseDate: "2026-09-25",
    description: "A restrained suspense thriller about a quiet town where people refuse to leave their homes after sunset.",
    director: "TBA",
    worldPremiere: "2026-09-18 — Toronto Midnight Preview",
    categories: ["Thriller", "Mystery"],
    mainCast: ["Cast TBA"],
    runtime: "99 min",
    releaseVenue: "Unseen Nairobi Rooftop Cinema"
  },
  {
    id: 98,
    title: "Your Mother, Your Mother, Your Mother",
    posterUrl: "https://image.tmdb.org/t/p/w500/b34jPzmB0wZy7EjUZoleXOl2RRI.jpg",
    publicReleaseDate: "2026-09-25",
    description: "An intergenerational drama-comedy about family stories, repeated mistakes, and the difficulty of breaking patterns.",
    director: "TBA",
    worldPremiere: "2026-09-14 — Toronto Special Presentation",
    categories: ["Drama", "Comedy", "Family"],
    mainCast: ["Cast TBA"],
    runtime: "108 min",
    releaseVenue: "Nairobi Film Centre"
  },
  {
    id: 99,
    title: "Princess Mononoke",
    posterUrl: "https://image.tmdb.org/t/p/w500/cMYCDADoLKLbB83g4WnJegaZimC.jpg",
    publicReleaseDate: "2026-09-26",
    description: "A theatrical re-release of Studio Ghibli’s epic animated fantasy about conflict between humans, forests, and ancient spirits.",
    director: "Hayao Miyazaki",
    worldPremiere: "1997-07-12 — Japan Theatrical Premiere",
    categories: ["Animation", "Fantasy", "Adventure", "Re-release"],
    mainCast: ["Yōji Matsuda", "Yuriko Ishida", "Yūko Tanaka"],
    runtime: "133 min",
    releaseVenue: "Unseen Nairobi Rooftop Cinema"
  },
  {
    id: 100,
    title: "Crawlers",
    posterUrl: "https://image.tmdb.org/t/p/w500/bCObr03CsKOOwKysoUL5teG8wmU.jpg",
    publicReleaseDate: "2026-10-02",
    description: "A creature-feature thriller about a town forced to defend itself after something emerges from below.",
    director: "TBA",
    worldPremiere: "2026-09-27 — Fantastic Fest Closing Night",
    categories: ["Horror", "Thriller", "Creature Feature"],
    mainCast: ["Cast TBA"],
    runtime: "101 min",
    releaseVenue: "Anga CBD, Nairobi"
  }
];
